config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :guests, only: [:index, :update]
  end
  resources :profiles
  resources :event_invites, only: [:create, :destroy]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  after_create_commit { broadcast_append_to('events', target: 'events', locals: { event: self}) }
  
  belongs_to :host, class_name: "User"
  has_many :event_invites, foreign_key: :invited_event_id
  has_many :guests, through: :event_invites, source: :event_guest

  validates :title, presence: true
  validates :location, presence: true

  scope :past_events, -> { where("date < ?", DateTime.now ) }
  scope :upcoming_events, -> { where("date > ?", DateTime.now ) }

end

app/models/event_invite.rb
class EventInvite < ApplicationRecord
  belongs_to :event_guest, class_name: "User"
  belongs_to :invited_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :hosted_events, foreign_key: "host_id", class_name: "Event"
  has_many :event_invites, foreign_key: :event_guest_id
  has_many :invited_events, through: :event_invites
  
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  self.responder = ApplicationResponder
  respond_to :html
end

app/controllers/event_invites_controller.rb
class EventInvitesController < ApplicationController
  def create
    @event = Event.find(params[:event_invite][:invited_event_id])

    if @event.guests.include?(params[:event_invite][:event_guest_id])
      redirect_to @event, notice: "You are already attending this event."
    else
      @event_invite = EventInvite.new(event_invite_params)

      if @event_invite.save
        redirect_to event_path(@event_invite.invited_event_id), notice: "You are now attending this event."
      else
        redirect_to event_path(@event_invite.invited_event_id), notice: "Oops, something whent wrong."
      end
    end
  end

  def destroy
    @event_invite = EventInvite.where(invited_event_id: params[:event_invite][:invited_event_id], event_guest_id: params[:event_invite][:event_guest_id]).first
    @event_invite.destroy

    respond_to do |format|
      format.html { redirect_to event_path(@event_invite.invited_event_id), notice: "You have been removed from the guest list." }
    end
  end

  private

  def event_invite_params
    params.require(:event_invite).permit(:invited_event_id, :event_guest_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.all.order(date: :asc)
  end

  
  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)
    current_user.hosted_events << @event

    respond_to do |format|
      if @event.save
        format.turbo_stream
        format.html { redirect_to @event, notice: "Event was successfully created." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@event)}_form", partial: "form", locals: { event: @event }) }
        format.html { render :new, status: :unprocessabile_entity }
      end
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(helpers.dom_id(@event), partial: "form", locals: { event: @event }) }
        format.html { render :new, status: :unprocessabile_entity }
      end
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully deleted." }
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :date, guest_ids:[])
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :get_users, :get_event

  def index
    @guests = @event.guests
  end

  private

  def get_users
    @users = User.all.order(name: :asc)
  end

  def get_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = User.all.order(name: :asc)
  end

  def show
    @profile = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_invites_helper.rb
module EventInvitesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/events/_event.html.erb
<tr id="<%= "#{dom_id event}_record" %>">
    <td><%= link_to event.title, event_path(event) %></td>
    <td><%= event.location %></td>
    <td><%= event.date.to_formatted_s(:long_ordinal) %></td>
</tr>

app/views/events/_event_link.html.erb
<%= link_to "New Event", new_event_path, class: "btn btn-primary w-1 mt-3 mb-3", data: { turbo: current_user ? true : false } %>

app/views/events/_event_table.html.erb
<h5>Upcoming Events</h5>
<% if events.upcoming_events.empty? %>
  <p>No events yet.</p>
<% else %>
  <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Event</th>
          <th scope="col">Location</th>
          <th scope="col">Date</th>
        </tr>
      </thead>
      <tbody id="events">
        <%= render events.upcoming_events %>
      </tbody>
  </table class="table">
<% end %>

<h5>Past Events</h5>
<% if events.past_events.empty? %>
  <p>No events yet.</p>
<% else %>
  <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Event</th>
          <th scope="col">Location</th>
          <th scope="col">Date</th>
        </tr>
      </thead>
      <tbody id="events">
        <%= render events.past_events %>
      </tbody>
  </table class="table">
<% end %>

app/views/events/_form.html.erb
<%= form_with model: event, id: "#{dom_id(event)}_form", class: "d-inline-flex gap-1 mt-3 mb-3" do |form| %>
  <% if event.errors.any? %>
    <div class="error">
      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group d-inline-flex align-items-center mb-4">
    <%= form.label :title, "Event Title:" %>
    <%= form.text_field :title, class: "event_form_title" %>
  </div>
  <div class="field form-group d-inline-flex align-items-center mb-4">
  <%= form.label :location, "Location:" %>
    <%= form.text_field :location, class: "event_form_location" %>
  </div>
  <div class="field form-group d-inline-flex align-items-center mb-4">
    <%= form.label :date, "Date:" %>
    <%= form.datetime_select :date, class: "event_form_title" %>
  </div>

  <div class="">
    <%= form.submit class: "event_submit btn btn-primary" %>
  </div>
<% end %>

app/views/events/_guests.html.erb
<ul>
    <% @event.guests.each do |guest| %>
      <li><%= link_to guest.name, profile_path(guest) %></li>
    <% end %>
</ul>

app/views/events/create.turbo_stream.erb
<%= turbo_stream.append "events" do %>
  <%= render "event", event: @event %>
<% end %>

<%= turbo_stream.replace "new_event" do %>
  <% render "event_link" %>
<% end %>

app/views/events/edit.html.erb
  <%= link_to event_path, class: "btn-close me-1" %>
  <%= render "form", event: @event, locals: { url: edit_event_path, method: :patch } %>

app/views/events/index.html.erb
<section class="events-section">
  <h1>Events</h1>

  <%= turbo_frame_tag "new_event" do %>
    <%= render "event_link" %>
  <% end %>

  <% if @events %>
    <%= render partial: "event_table", locals: { events: @events } %>
  <% else %>
    <p>There are no events yet.</p>
  <% end %>

</section>

app/views/events/new.html.erb
<%= turbo_frame_tag "new_event" do %>
  <%= link_to "", root_path, class: "btn-close me-1" %>
  <%= render "form", event: Event.new, locals: { url: events_path } %>
<% end %>

app/views/events/show.html.erb
<section>
  <h1><%= @event.title %></h1>

  <p>Hosted by: <%= link_to @event.host.name, profile_path(@event.host) %></p>

  <h3><%= @event.location %></h3>
  <h4 class="mb-4"><%= @event.date.to_formatted_s(:long_ordinal) %></h4>

  <div class="d-inline-flex align-items-center gap-3">
    <h3>Guests:</h3>
    <% if user_signed_in? && current_user == @event.host %>
      <%= link_to "Edit Guestlist", event_guests_path(@event) %>
    <% end %>
  </div>

  <% if @event.guests.empty? %>
    <p>No guests have joined this party yet. Get this party started and join!</p>
  <% else %>
    <%= render "guests" %>
  <% end %>

  <% if @event.guests.include?(current_user)%>
    <%= button_to "Leave Party", event_invite_path, method: :delete, params: { event_invite: {invited_event_id: @event, event_guest_id: current_user} }, class: "btn btn-warning" %>
  <% else %>
    <%= button_to "Join Party", event_invites_path, params: { event_invite: {invited_event_id: @event, event_guest_id: current_user} }, class: "btn btn-success" %>
  <% end %>

  <% if user_signed_in? && current_user == @event.host %>
    <div class="d-inline-flex align-items-center gap-3 mt-4">
      <%= link_to "Edit", edit_event_path(@event) %>
      <%= button_to "Delete", event_path(@event), method: :delete, data: { turbo_confirm: "Are you sure you want to delete this event?" },  class: "btn btn-danger" %>
    </div>
  <% end %>
</section>

app/views/guests/index.html.erb
<h1><%= @event.title %> Guest List</h1>

<%= form_with model: @event, url: "/events/#{@event.id}", method: :patch do |form| %>
  <%= hidden_field_tag "event[guest_ids][]", nil %>

  <% @users.each do |user| %>
    <%= check_box_tag "event[guest_ids][]", user.id, @event.guests.include?(user), id: "user_#{user.id}" %>
    <%= label_tag dom_id(user), user.name %><br>
  <% end %>

  <%= form.hidden_field :title, value: @event.title %>
  <%= form.hidden_field :location, value: @event.location %>
  <%= form.hidden_field :date, value: @event.date %>

  <div class="mt-3">
    <%= form.submit class: "event_submit btn btn-primary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-4">
      <%= link_to "Private Events", events_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Events", events_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Party People", profiles_path, class: "nav-link" %>
          </li>
        </ul>
        <div class="nav navbar-nav ms-auto">
          <% if current_user %>
            <div class="navbar-text">
              <p class="me-2">Logged in as <%= link_to "#{current_user.name}", profile_path(current_user) %></p>
            </div>
            <div class="nav-item">
              <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-primary sign-out-btn" %>
            </div>
          <% else %>
            <div class="nav-item">
              <%= link_to "Log In", new_user_session_path, class: "nav-link mr-4" %>
            </div>
            <div class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary sign-up-btn" %>
            </div>
          <% end %>
        </div>
      </div>
    </nav>

    <% if notice %>
      <p class="notice alert alert-success position-absolute w-100"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-warning position-absolute w-100" role="alert"><%= alert %></p>
    <% end %>

    <main class="row d-flex justify-content-center p-4 mt-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>Party People</h1>

<ul class="list-unstyled ms-4">
  <% @profiles.each do |profile| %>
    <li><%= link_to profile.name, profile_path(profile) %></li>
  <% end %>
</ul>

app/views/profiles/show.html.erb
<section>
  <h1><%= @profile.name %></h1>

  <% if current_user && current_user.id == @profile.id %>
    <%= render "events/event_link" %>
  <% end %>

  <div class="my-4">
    <h3>Hosted Events</h3>
    <% if @profile.hosted_events.empty? %>
      <p>This user hasn't hosted any events yet.</p>
    <% else %>
      <%= render partial: "events/event_table", locals: { events: @profile.hosted_events } %>
    <% end %>
  </div>

  <div class="my-4">
    <h3>Invited Events</h3>
    <% if @profile.invited_events.empty? %>
      <p>This user hasn't attended any events yet.</p>
    <% else %>
      <%= render partial: "events/event_table", locals: { events: @profile.invited_events } %>
    <% end %>
  </div>
</section>